config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'
  resources :recorridos
  resources :ruta
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recorrido.rb
class Recorrido < ApplicationRecord
end

app/models/rutum.rb
class Rutum < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/recorridos_controller.rb
class RecorridosController < ApplicationController
  before_action :set_recorrido, only: [:show, :edit, :update, :destroy]

  # GET /recorridos
  # GET /recorridos.json
  def index
    @recorridos = Recorrido.all
  end

  # GET /recorridos/1
  # GET /recorridos/1.json
  def show
  end

  # GET /recorridos/new
  def new
    @recorrido = Recorrido.new
  end

  # GET /recorridos/1/edit
  def edit
  end

  # POST /recorridos
  # POST /recorridos.json
  def create
    @recorrido = Recorrido.new(recorrido_params)

    respond_to do |format|
      if @recorrido.save
        format.html { redirect_to @recorrido, notice: 'Recorrido was successfully created.' }
        format.json { render :show, status: :created, location: @recorrido }
      else
        format.html { render :new }
        format.json { render json: @recorrido.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recorridos/1
  # PATCH/PUT /recorridos/1.json
  def update
    respond_to do |format|
      if @recorrido.update(recorrido_params)
        format.html { redirect_to @recorrido, notice: 'Recorrido was successfully updated.' }
        format.json { render :show, status: :ok, location: @recorrido }
      else
        format.html { render :edit }
        format.json { render json: @recorrido.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recorridos/1
  # DELETE /recorridos/1.json
  def destroy
    @recorrido.destroy
    respond_to do |format|
      format.html { redirect_to recorridos_url, notice: 'Recorrido was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recorrido
      @recorrido = Recorrido.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recorrido_params
      params.require(:recorrido).permit(:Lugar, :descripcion)
    end
end

app/controllers/ruta_controller.rb
class RutaController < ApplicationController
  before_action :set_rutum, only: [:show, :edit, :update, :destroy]

  # GET /ruta
  # GET /ruta.json
  def index
    @ruta = Rutum.all
  end

  # GET /ruta/1
  # GET /ruta/1.json
  def show
  end

  # GET /ruta/new
  def new
    @rutum = Rutum.new
  end

  # GET /ruta/1/edit
  def edit
  end

  # POST /ruta
  # POST /ruta.json
  def create
    @rutum = Rutum.new(rutum_params)

    respond_to do |format|
      if @rutum.save
        format.html { redirect_to @rutum, notice: 'Rutum was successfully created.' }
        format.json { render :show, status: :created, location: @rutum }
      else
        format.html { render :new }
        format.json { render json: @rutum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ruta/1
  # PATCH/PUT /ruta/1.json
  def update
    respond_to do |format|
      if @rutum.update(rutum_params)
        format.html { redirect_to @rutum, notice: 'Rutum was successfully updated.' }
        format.json { render :show, status: :ok, location: @rutum }
      else
        format.html { render :edit }
        format.json { render json: @rutum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ruta/1
  # DELETE /ruta/1.json
  def destroy
    @rutum.destroy
    respond_to do |format|
      format.html { redirect_to ruta_url, notice: 'Rutum was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rutum
      @rutum = Rutum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rutum_params
      params.require(:rutum).permit(:nombre, :descripcion)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recorridos_helper.rb
module RecorridosHelper
end

app/helpers/ruta_helper.rb
module RutaHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ruta</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Rutas Turísticas Bogotá</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Inicio <span class="sr-only">(current)</span></a>
      </li>
        <li class="nav-item active">
        <a class="nav-link" href="#">Rutas <span class="sr-only">(current)</span></a>
      </li
       <li class="nav-item active">
        <a class="nav-link" href="#">Tips <span class="sr-only">(current)</span></a>
      </li
     <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true"></a>
      </li>
      
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true"></a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
    <%= yield %>
  </body>
</html>

app/views/recorridos/_form.html.erb
<%= form_with(model: recorrido, local: true) do |form| %>
  <% if recorrido.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recorrido.errors.count, "error") %> prohibited this recorrido from being saved:</h2>

      <ul>
        <% recorrido.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Lugar %>
    <%= form.text_field :Lugar %>
  </div>

  <div class="field">
    <%= form.label :descripcion %>
    <%= form.text_area :descripcion %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/recorridos/edit.html.erb
<h1>Editing Recorrido</h1>

<%= render 'form', recorrido: @recorrido %>

<%= link_to 'Show', @recorrido %> |
<%= link_to 'Back', recorridos_path %>

app/views/recorridos/index.html.erb
<p id="notice"><%= notice %></p>

  <tbody>
  

<h1>Recorridos</h1>

<table>
  <thead>
    <tr>
      <th>Lugar</th>
      <th>Descripcion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
    <% @recorridos.each do |recorrido| %>
      <tr>
        <td><%= recorrido.Lugar %></td>
        <td><%= recorrido.descripcion %></td>
        <td><%= link_to 'Show', recorrido %></td>
        <td><%= link_to 'Edit', edit_recorrido_path(recorrido) %></td>
        <td><%= link_to 'Destroy', recorrido, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recorrido', new_recorrido_path %>

app/views/recorridos/new.html.erb
<h1>New Recorrido</h1>

<%= render 'form', recorrido: @recorrido %>

<%= link_to 'Back', recorridos_path %>

app/views/recorridos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Lugar:</strong>
  <%= @recorrido.Lugar %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @recorrido.descripcion %>
</p>

<%= link_to 'Edit', edit_recorrido_path(@recorrido) %> |
<%= link_to 'Back', recorridos_path %>

app/views/ruta/_form.html.erb
<%= form_with(model: rutum, local: true) do |form| %>
  <% if rutum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rutum.errors.count, "error") %> prohibited this rutum from being saved:</h2>

      <ul>
        <% rutum.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="field">
    <%= form.label :descripcion %>
    <%= form.text_area :descripcion %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ruta/edit.html.erb
<h1>Editing Rutum</h1>

<%= render 'form', rutum: @rutum %>

<%= link_to 'Show', @rutum %> |
<%= link_to 'Back', ruta_path %>

app/views/ruta/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ruta</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripcion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ruta.each do |rutum| %>
      <tr>
        <td><%= rutum.nombre %></td>
        <td><%= rutum.descripcion %></td>
        <td><%= link_to 'Show', rutum %></td>
        <td><%= link_to 'Edit', edit_rutum_path(rutum) %></td>
        <td><%= link_to 'Destroy', rutum, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rutum', new_rutum_path %>

app/views/ruta/new.html.erb
<h1>New Rutum</h1>

<%= render 'form', rutum: @rutum %>

<%= link_to 'Back', ruta_path %>

app/views/ruta/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @rutum.nombre %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @rutum.descripcion %>
</p>

<%= link_to 'Edit', edit_rutum_path(@rutum) %> |
<%= link_to 'Back', ruta_path %>

app/views/welcome/index.html.erb
<h1></h1>
<p></p>